# Generated by Django 6.0.4 on 2026-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savinggoals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savinggoals',
            old_name='deletegoal',
            new_name='goal_name',
        ),
        migrations.RenameField(
            model_name='savinggoals',
            old_name='amount',
            new_name='target_amount',
        ),
        migrations.RemoveField(
            model_name='savinggoals',
            name='goalcreate',
        ),
        migrations.AddField(
            model_name='savinggoals',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
