# Generated by Django 6.0.5 on 2026-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savinggoals', '0002_rename_deletegoal_savinggoals_goal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savinggoals',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='savinggoals',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
