# Generated by Django 6.0.5 on 2026-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_phone',
            field=models.CharField(max_length=11),
        ),
    ]
