# Generated by Django 6.0.5 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_receiver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
