# Generated by Django 6.0.5 on 2026-05-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='cover_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='circle_covers/'),
        ),
    ]
